
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CustomSlider': typeof import("../components/CustomSlider.vue")['default']
    'IconsFacebook': typeof import("../components/Icons/facebook.vue")['default']
    'IconsGray': typeof import("../components/Icons/gray.vue")['default']
    'IconsGreenok': typeof import("../components/Icons/greenok.vue")['default']
    'IconsHeadset': typeof import("../components/Icons/headset.vue")['default']
    'IconsInfo': typeof import("../components/Icons/info.vue")['default']
    'IconsInstagram': typeof import("../components/Icons/instagram.vue")['default']
    'IconsLighting': typeof import("../components/Icons/lighting.vue")['default']
    'IconsLinkedin': typeof import("../components/Icons/linkedin.vue")['default']
    'IconsMail': typeof import("../components/Icons/mail.vue")['default']
    'IconsRight': typeof import("../components/Icons/right.vue")['default']
    'IconsRightold': typeof import("../components/Icons/rightold.vue")['default']
    'IconsSearch': typeof import("../components/Icons/search.vue")['default']
    'IconsSolar': typeof import("../components/Icons/solar.vue")['default']
    'IconsTwitter': typeof import("../components/Icons/twitter.vue")['default']
    'IconsWhiteright': typeof import("../components/Icons/whiteright.vue")['default']
    'IconsWind': typeof import("../components/Icons/wind.vue")['default']
    'IconsYoutube': typeof import("../components/Icons/youtube.vue")['default']
    'LayoutsFooter': typeof import("../components/Layouts/Footer.vue")['default']
    'LayoutsHeader': typeof import("../components/Layouts/Header.vue")['default']
    'ModuleContainer': typeof import("../components/module/Container.vue")['default']
    'ModuleHomeCardslider': typeof import("../components/module/HomeCardslider.vue")['default']
    'ModuleHomeEnergy': typeof import("../components/module/HomeEnergy.vue")['default']
    'ModuleHomeEss': typeof import("../components/module/HomeEss.vue")['default']
    'ModuleHomeFuture': typeof import("../components/module/HomeFuture.vue")['default']
    'ModuleHomeMore': typeof import("../components/module/HomeMore.vue")['default']
    'ModuleHomeSlider': typeof import("../components/module/HomeSlider.vue")['default']
    'ModuleHomeSocial': typeof import("../components/module/HomeSocial.vue")['default']
    'ModuleHomeTab': typeof import("../components/module/HomeTab.vue")['default']
    'ModuleHomeTabSection': typeof import("../components/module/HomeTabSection.vue")['default']
    'ModuleSocialSlider': typeof import("../components/module/SocialSlider.vue")['default']
    'ModuleSocialSlidersss': typeof import("../components/module/SocialSlidersss.vue")['default']
    'ModuleExampleListModule': typeof import("../components/module/exampleListModule.vue")['default']
    'ModuleExampleModule': typeof import("../components/module/exampleModule.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCustomSlider': typeof import("../components/CustomSlider.vue")['default']
    'LazyIconsFacebook': typeof import("../components/Icons/facebook.vue")['default']
    'LazyIconsGray': typeof import("../components/Icons/gray.vue")['default']
    'LazyIconsGreenok': typeof import("../components/Icons/greenok.vue")['default']
    'LazyIconsHeadset': typeof import("../components/Icons/headset.vue")['default']
    'LazyIconsInfo': typeof import("../components/Icons/info.vue")['default']
    'LazyIconsInstagram': typeof import("../components/Icons/instagram.vue")['default']
    'LazyIconsLighting': typeof import("../components/Icons/lighting.vue")['default']
    'LazyIconsLinkedin': typeof import("../components/Icons/linkedin.vue")['default']
    'LazyIconsMail': typeof import("../components/Icons/mail.vue")['default']
    'LazyIconsRight': typeof import("../components/Icons/right.vue")['default']
    'LazyIconsRightold': typeof import("../components/Icons/rightold.vue")['default']
    'LazyIconsSearch': typeof import("../components/Icons/search.vue")['default']
    'LazyIconsSolar': typeof import("../components/Icons/solar.vue")['default']
    'LazyIconsTwitter': typeof import("../components/Icons/twitter.vue")['default']
    'LazyIconsWhiteright': typeof import("../components/Icons/whiteright.vue")['default']
    'LazyIconsWind': typeof import("../components/Icons/wind.vue")['default']
    'LazyIconsYoutube': typeof import("../components/Icons/youtube.vue")['default']
    'LazyLayoutsFooter': typeof import("../components/Layouts/Footer.vue")['default']
    'LazyLayoutsHeader': typeof import("../components/Layouts/Header.vue")['default']
    'LazyModuleContainer': typeof import("../components/module/Container.vue")['default']
    'LazyModuleHomeCardslider': typeof import("../components/module/HomeCardslider.vue")['default']
    'LazyModuleHomeEnergy': typeof import("../components/module/HomeEnergy.vue")['default']
    'LazyModuleHomeEss': typeof import("../components/module/HomeEss.vue")['default']
    'LazyModuleHomeFuture': typeof import("../components/module/HomeFuture.vue")['default']
    'LazyModuleHomeMore': typeof import("../components/module/HomeMore.vue")['default']
    'LazyModuleHomeSlider': typeof import("../components/module/HomeSlider.vue")['default']
    'LazyModuleHomeSocial': typeof import("../components/module/HomeSocial.vue")['default']
    'LazyModuleHomeTab': typeof import("../components/module/HomeTab.vue")['default']
    'LazyModuleHomeTabSection': typeof import("../components/module/HomeTabSection.vue")['default']
    'LazyModuleSocialSlider': typeof import("../components/module/SocialSlider.vue")['default']
    'LazyModuleSocialSlidersss': typeof import("../components/module/SocialSlidersss.vue")['default']
    'LazyModuleExampleListModule': typeof import("../components/module/exampleListModule.vue")['default']
    'LazyModuleExampleModule': typeof import("../components/module/exampleModule.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CustomSlider: typeof import("../components/CustomSlider.vue")['default']
export const IconsFacebook: typeof import("../components/Icons/facebook.vue")['default']
export const IconsGray: typeof import("../components/Icons/gray.vue")['default']
export const IconsGreenok: typeof import("../components/Icons/greenok.vue")['default']
export const IconsHeadset: typeof import("../components/Icons/headset.vue")['default']
export const IconsInfo: typeof import("../components/Icons/info.vue")['default']
export const IconsInstagram: typeof import("../components/Icons/instagram.vue")['default']
export const IconsLighting: typeof import("../components/Icons/lighting.vue")['default']
export const IconsLinkedin: typeof import("../components/Icons/linkedin.vue")['default']
export const IconsMail: typeof import("../components/Icons/mail.vue")['default']
export const IconsRight: typeof import("../components/Icons/right.vue")['default']
export const IconsRightold: typeof import("../components/Icons/rightold.vue")['default']
export const IconsSearch: typeof import("../components/Icons/search.vue")['default']
export const IconsSolar: typeof import("../components/Icons/solar.vue")['default']
export const IconsTwitter: typeof import("../components/Icons/twitter.vue")['default']
export const IconsWhiteright: typeof import("../components/Icons/whiteright.vue")['default']
export const IconsWind: typeof import("../components/Icons/wind.vue")['default']
export const IconsYoutube: typeof import("../components/Icons/youtube.vue")['default']
export const LayoutsFooter: typeof import("../components/Layouts/Footer.vue")['default']
export const LayoutsHeader: typeof import("../components/Layouts/Header.vue")['default']
export const ModuleContainer: typeof import("../components/module/Container.vue")['default']
export const ModuleHomeCardslider: typeof import("../components/module/HomeCardslider.vue")['default']
export const ModuleHomeEnergy: typeof import("../components/module/HomeEnergy.vue")['default']
export const ModuleHomeEss: typeof import("../components/module/HomeEss.vue")['default']
export const ModuleHomeFuture: typeof import("../components/module/HomeFuture.vue")['default']
export const ModuleHomeMore: typeof import("../components/module/HomeMore.vue")['default']
export const ModuleHomeSlider: typeof import("../components/module/HomeSlider.vue")['default']
export const ModuleHomeSocial: typeof import("../components/module/HomeSocial.vue")['default']
export const ModuleHomeTab: typeof import("../components/module/HomeTab.vue")['default']
export const ModuleHomeTabSection: typeof import("../components/module/HomeTabSection.vue")['default']
export const ModuleSocialSlider: typeof import("../components/module/SocialSlider.vue")['default']
export const ModuleSocialSlidersss: typeof import("../components/module/SocialSlidersss.vue")['default']
export const ModuleExampleListModule: typeof import("../components/module/exampleListModule.vue")['default']
export const ModuleExampleModule: typeof import("../components/module/exampleModule.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCustomSlider: typeof import("../components/CustomSlider.vue")['default']
export const LazyIconsFacebook: typeof import("../components/Icons/facebook.vue")['default']
export const LazyIconsGray: typeof import("../components/Icons/gray.vue")['default']
export const LazyIconsGreenok: typeof import("../components/Icons/greenok.vue")['default']
export const LazyIconsHeadset: typeof import("../components/Icons/headset.vue")['default']
export const LazyIconsInfo: typeof import("../components/Icons/info.vue")['default']
export const LazyIconsInstagram: typeof import("../components/Icons/instagram.vue")['default']
export const LazyIconsLighting: typeof import("../components/Icons/lighting.vue")['default']
export const LazyIconsLinkedin: typeof import("../components/Icons/linkedin.vue")['default']
export const LazyIconsMail: typeof import("../components/Icons/mail.vue")['default']
export const LazyIconsRight: typeof import("../components/Icons/right.vue")['default']
export const LazyIconsRightold: typeof import("../components/Icons/rightold.vue")['default']
export const LazyIconsSearch: typeof import("../components/Icons/search.vue")['default']
export const LazyIconsSolar: typeof import("../components/Icons/solar.vue")['default']
export const LazyIconsTwitter: typeof import("../components/Icons/twitter.vue")['default']
export const LazyIconsWhiteright: typeof import("../components/Icons/whiteright.vue")['default']
export const LazyIconsWind: typeof import("../components/Icons/wind.vue")['default']
export const LazyIconsYoutube: typeof import("../components/Icons/youtube.vue")['default']
export const LazyLayoutsFooter: typeof import("../components/Layouts/Footer.vue")['default']
export const LazyLayoutsHeader: typeof import("../components/Layouts/Header.vue")['default']
export const LazyModuleContainer: typeof import("../components/module/Container.vue")['default']
export const LazyModuleHomeCardslider: typeof import("../components/module/HomeCardslider.vue")['default']
export const LazyModuleHomeEnergy: typeof import("../components/module/HomeEnergy.vue")['default']
export const LazyModuleHomeEss: typeof import("../components/module/HomeEss.vue")['default']
export const LazyModuleHomeFuture: typeof import("../components/module/HomeFuture.vue")['default']
export const LazyModuleHomeMore: typeof import("../components/module/HomeMore.vue")['default']
export const LazyModuleHomeSlider: typeof import("../components/module/HomeSlider.vue")['default']
export const LazyModuleHomeSocial: typeof import("../components/module/HomeSocial.vue")['default']
export const LazyModuleHomeTab: typeof import("../components/module/HomeTab.vue")['default']
export const LazyModuleHomeTabSection: typeof import("../components/module/HomeTabSection.vue")['default']
export const LazyModuleSocialSlider: typeof import("../components/module/SocialSlider.vue")['default']
export const LazyModuleSocialSlidersss: typeof import("../components/module/SocialSlidersss.vue")['default']
export const LazyModuleExampleListModule: typeof import("../components/module/exampleListModule.vue")['default']
export const LazyModuleExampleModule: typeof import("../components/module/exampleModule.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
